/* ---- Where each town's council publishes its agendas ----
   119 Ontario municipalities publish their council and committee meetings
   through eSCRIBE, at pub-<name>.escribemeetings.com. Found on 22 September
   2026 by trying every municipality's name against that pattern, then
   opening the portals whose names are shared with places elsewhere and
   reading the meeting locations. Three were dropped on that check:
   pub-cityofdawson is Dawson City, Yukon; pub-cochrane is Cochrane, Alberta;
   and Kingsville's portal exists but holds no meetings.

   This is public record — the agenda a council is legally required to
   publish before it meets. It is shown as exactly that, never as news. */

export const ESCRIBE = {
  "Adelaide Metcalfe": "adelaidemetcalfe",
  "Amaranth": "amaranth",
  "Amherstburg": "amherstburg",
  "Arran–Elderslie": "arranelderslie",
  "Assiginack": "assiginack",
  "Augusta": "augusta",
  "Barrie": "barrie",
  "Blandford-Blenheim": "blandfordblenheim",
  "Blind River": "blindriver",
  "Bradford West Gwillimbury": "bradfordwestgwillimbury",
  "Brampton": "brampton",
  "Brant": "brant",
  "Brantford": "brantford",
  "Brockton": "brockton",
  "Caledon": "caledon",
  "Cambridge": "cambridge",
  "Carleton Place": "carletonplace",
  "Casselman": "casselman",
  "Cavan Monaghan": "cavanmonaghan",
  "Champlain": "champlain",
  "Chatham-Kent": "chatham-kent",
  "Chatsworth": "chatsworth",
  "Clarington": "clarington",
  "Clearview": "clearview",
  "Cobourg": "cobourg",
  "Collingwood": "collingwood",
  "Cornwall": "cornwall",
  "Cramahe": "cramahe",
  "Douro-Dummer": "douro-dummer",
  "Dryden": "dryden",
  "Dutton/Dunwich": "duttondunwich",
  "East Ferris": "eastferris",
  "East Garafraxa": "eastgarafraxa",
  "East Hawkesbury": "easthawkesbury",
  "Elliot Lake": "elliotlake",
  "Erin": "erin",
  "Espanola": "espanola",
  "Fort Erie": "forterie",
  "Georgian Bluffs": "georgianbluffs",
  "Georgina": "georgina",
  "Goderich": "goderich",
  "Grand Valley": "townofgrandvalley",
  "Greater Sudbury": "greatersudbury",
  "Grimsby": "grimsby",
  "Guelph": "guelph",
  "Halton Hills": "haltonhills",
  "Hamilton": "hamilton",
  "Hanover": "hanover",
  "Hawkesbury": "hawkesbury",
  "Huron Shores": "huronshores",
  "Huron-Kinloss": "huronkinloss",
  "Kawartha Lakes": "kawarthalakes",
  "Kenora": "kenora",
  "Kincardine": "kincardine",
  "King": "king",
  "Kingston": "cityofkingston",
  "Kitchener": "kitchener",
  "LaSalle": "lasalle",
  "Lakeshore": "lakeshore",
  "Lambton Shores": "lambtonshores",
  "Lanark Highlands": "lanarkhighlands",
  "Lincoln": "lincoln",
  "London": "london",
  "Lucan Biddulph": "lucanbiddulph",
  "Moonbeam": "moonbeam",
  "Newmarket": "newmarket",
  "North Bay": "northbay",
  "North Dundas": "northdundas",
  "North Glengarry": "northglengarry",
  "North Grenville": "northgrenville",
  "North Middlesex": "northmiddlesex",
  "North Perth": "northperth",
  "Oakville": "oakville",
  "Orangeville": "orangeville",
  "Oshawa": "oshawa",
  "Ottawa": "ottawa",
  "Owen Sound": "owensound",
  "Perth East": "pertheast",
  "Peterborough": "peterborough",
  "Pickering": "pickering",
  "Point Edward": "pointedward",
  "Port Colborne": "portcolborne",
  "Port Hope": "porthope",
  "Prescott": "prescott",
  "Renfrew": "renfrew",
  "Richmond Hill": "richmondhill",
  "Rideau Lakes": "rideaulakes",
  "Saugeen Shores": "saugeenshores",
  "Scugog": "scugog",
  "Shelburne": "shelburne",
  "Smiths Falls": "smithsfalls",
  "South Dundas": "southdundas",
  "South Glengarry": "southglengarry",
  "South Huron": "southhuron",
  "South Stormont": "southstormont",
  "Southgate": "southgate",
  "Southwest Middlesex": "southwestmiddlesex",
  "St. Catharines": "stcatharines",
  "St. Thomas": "stthomas",
  "Stratford": "stratford",
  "Strathroy-Caradoc": "strathroy-caradoc",
  "Temiskaming Shores": "temiskamingshores",
  "Thames Centre": "thamescentre",
  "The Archipelago": "thearchipelago",
  "The Nation": "thenation",
  "Thorold": "thorold",
  "Thunder Bay": "thunderbay",
  "Tillsonburg": "tillsonburg",
  "Tweed": "tweed",
  "Uxbridge": "uxbridge",
  "Vaughan": "vaughan",
  "Wasaga Beach": "wasagabeach",
  "Welland": "welland",
  "Wellesley": "wellesley",
  "Wellington North": "wellington-north",
  "West Elgin": "westelgin",
  "West Grey": "westgrey",
  "West Lincoln": "westlincoln",
  "Whitby": "whitby",
};

export function councilPortal(townName) {
  const sub = ESCRIBE[townName];
  return sub ? `https://pub-${sub}.escribemeetings.com` : null;
}
